import React from 'react';
import Head from 'next/head'
import { urlFor } from '@/lib/sanity';
import Link from 'next/link'
import Navigation from '@/components/Shared/Navigation';
import Footer from '@/components/Shared/Footer/footer';
import Quantitycounter from '@/components/Shared/quantityCounter';
import { useGlobalContext } from '@/ Context/context';

const Cart = () => {
  const {cartInfo} = useGlobalContext()
 console.log(cartInfo)




  return (
    <>
      <Head>
        <title>Cart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation/>


      <main>
        <div className="container mx-auto p-24">
          {cartInfo.length ? 
            <>
              <div className="flex flex-row gap-20 justify-end">
                <p>Quantity</p>
                <p>Price</p>
                <p>Total</p>
              </div>
              <div className="flex flex-col gap-8 justify-center">
                {cartInfo.map((items, index)=> {
                  const{ brandName, productName, price, image, quantity, id } = items
                  return (
                    <div className="flex flex-row justify-between" key={index}>
                      <div>
                        <div className="flex gap-4">
                          <div>
                            <img src={urlFor(image)} alt="" className="cartImage"/>
                          </div>
                          <div className="flex flex-col gap-4">
                            <h1 className="text-lg">Brand Name: <span className="font-bold">{brandName}</span></h1>
                            <p className="text-2xl ">Item: {productName}</p>
                          </div>
                        </div>
                      </div>

                      <div className="flex gap-20">
                        <div>
                          <Quantitycounter quantity={quantity}/>
                        </div>

                        <div>
                          <h1 className="text-2xl font-bold">${price}</h1>
                        </div>

                        <div>
                          <h1 className="text-2xl font-bold">${price * quantity}</h1>
                        </div>
                      </div>
                      
                    </div>
                  )
                })
                }
              </div>
            </>
          : 
          <div className="text-center">
            <div className="flex justify-center">
              <img src='/images/shopping-cart-10925.png' alt='' width='120px' />
            </div>
            <div className="mt-4">
            <h1 className="text-6xl font-bold text-zinc-700">Cart is Empty</h1>
            </div>
            <div className="mt-24">
            <button className="text-2xl btn"><Link href='/shop'>Back To Shop</Link></button>
            </div>
          </div>          
        }
        </div>
      </main>
       
        
     <Footer/>

      

    </>
  );
}

export default Cart;
