import React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Navigation from '@/components/Shared/Navigation';
import Footer from '@/components/Shared/Footer/footer';
import { useGlobalContext } from '@/ Context/context';
import { useSelector, useDispatch } from 'react-redux'
import { onRemove, toggleCartItemQuantity } from '../../store'
import { FaMinus, FaPlus } from 'react-icons/fa';


const Cart = () => {


  const cartItems = useSelector((state) => state.cart)
  const cartQuantity = useSelector((state) => state.totalQuantity)
  const quantity = useSelector((state) => state.quantity)
  const totalPrice = useSelector((state) => state.totalPrice)
  const dispatch = useDispatch();



  function handleRemove(_id) {
    console.log(_id)
    dispatch(onRemove({ _id }))
  }

  function handleToggle(_id, value) {
    dispatch(toggleCartItemQuantity({
      _id,
      value
    }))
  }


  return (
    <>
      <Head>
        <title>Cart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />


      <main>
        <div className="container mx-auto px-4 sm:px-6 lg:px-8 mb-12">
          {cartItems.length ?
            <>
              <h1 className="text-xl sm:text-2xl md:text-3xl font-bold text-zinc-700">Your Cart</h1>
            
              <div className="flex flex-col gap-8 justify-center">
                {cartItems.map((items, index) => {
                  console.log(cartItems)
                  const { vendor, title, price, images, quantity, _id } = items


                  return (
                    <div key={index}>
                      <div className="flex flex-col justify-between text-zinc-700" >
                        <div>
                          <div className="flex gap-4">
                              <div>
                                <Image src={images} alt={title} width="200" height="200" className="cartImage" />
                              </div>
                              <div className="flex flex-col gap-4">
                                <h1 className="text-lg"><span className="font-bold">{vendor}</span></h1>
                                <p className="text-md ">Item: {title}</p>
                              <div className="flex gap-4 ">
                                <FaPlus className="" onClick={() => { handleToggle(_id, 'inc') }} />
                                <span className="text-lg">{quantity}</span>
                                <FaMinus className="flex" onClick={() => { handleToggle(id, 'dec') }} />
                              </div>
                              <div>
                                <h1 className="text-xl">${price}</h1>
                              </div>
                              <div className=" text-zinc-700 font-bold underline">
                                <button onClick={() => handleRemove(_id)}>
                                  <p>On Remove</p>
                                </button>
                              </div>
                            </div>
                          </div>
                        </div>

                    


                      </div>
                    </div>
                  )
                })

                }
                <div className="flex justify-between text-zinc-700">
                  <h1 className="text-2xl">Subtotal</h1>
                  <p className="text-2xl font-bold">${totalPrice}</p>
                </div>
              </div>
              <div className="my-24 flex justify-end">
                <button className="btn">Checkout</button>
              </div>
            </>
            :
            <div className="text-center">
              <div className="flex justify-center">
                <Image src='/images/shopping-cart-10925.png' width={40} height={40} alt="shopping cart icon" />
              </div>
              <div className="mt-4">
                <h1 className="text-6xl font-bold text-zinc-700">Cart is Empty</h1>
              </div>
              <div className="mt-24">
                <button className="text-2xl btn"><Link href='/shop'>Back To Shop</Link></button>
              </div>
            </div>
          }
        </div>
      </main>
      <Footer />
    </>
  );
}

export default Cart;
