import PortableTextComponent from '@/components/Shared/PortableTextComponent';
import { sanityClient } from '@/lib/dist/sanity.dev';
import React from 'react';
import Image from 'next/image'
import Navigation from '@/components/Shared/Navigation';
import Head from 'next/head'
import Footer from '@/components/Shared/Footer/footer';
import RespMenu from '@/components/responsiveMenu/RespMenu'
import { useGlobalContext } from '@/ Context/context'

const About = ({data}) => {
  const {isOpenMenu} = useGlobalContext()

  const{about} = data
 
  const [aboutUs] = about
  


  return (
    <>
    <Head>
       <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>

    {isOpenMenu && <RespMenu/> } 
    <Navigation/>

    <main className="section-background">
    <div className="p-8 md:p-12 lg:p-24 flex flex-col gap-20">
      <div className="flex md:flex-row flex-col gap-20 text-zinc-700 ">
        <article className=" leading-loose text-lg w-fit md:w-1/2 items-center text-zinc-700">
          <PortableTextComponent detail={aboutUs}/>
        </article>
        

        <div className="">
          <Image src={about[0].aboutImage} width="200" height="200" alt="" className="aboutImage" unoptimized priority/>
        </div>
      </div>
    </div>
    </main>


    <Footer/>
    </>
  );
}

export default About;



const aboutInfo = `*[_type == 'about']{
  "aboutImage":image.asset->url,
  post,
  aboutus
}`

export async function getStaticProps() {
  const about = await sanityClient.fetch(aboutInfo)

  return {
    props: {
      data: {about}
    }
  }
}

