import React from 'react'
import Head from 'next/head'
import Navigation from '@/components/Shared/Navigation';

const Login = () => {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation/>
      <main>
        <div>
          <section>

          </section>
          <section>

          </section>
        </div>
      </main>
    </>
  )


}


export default Login