import React from 'react';
import Navigation from '@/components/Shared/Navigation'
import Head from 'next/head'
import ContactForm from '../../components/Shared/Forms/ContactForm'
import Footer from '@/components/Shared/Footer/footer'
import RespMenu from '@/components/responsiveMenu/RespMenu'
import Login from '@/components/Authorization/Login';
import Register from '@/components/Authorization/Register'
import { useGlobalContext } from '@/ Context/context';

const Contact = () => {
  const {isOpenMenu, isSignIn, isUserRegistered} = useGlobalContext()


  return (
  <>
    <Head>
      <title>Contact Us</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Navigation/>

    {isOpenMenu && <RespMenu/> }
    {isSignIn && <Login/>}
    {isUserRegistered && <Register/>}

    <main className="section-background">
      <div className="py-28">
        <div className="container mx-auto flex flex-col md:flex-row gap-24">
          <div className="mx-auto lg:m-0 w-2/4 text-zinc-700 text-lg leading-loose">
            <h1 className="mb-2 text-4xl font-bold">Get in Touch</h1>
            <p> 
               We respond to each and every message as soon as possible; it may take 2-3 business days for us to get back to you via email. PS. We recommend adding info@retrogoldlife.com to your contacts to ensure our responses land in your inbox.
            </p>
            <br></br>

            <div className="leading-loose">
            <h2>In the meantime, here is some information that may answer your question</h2>

            <h2 className="text-2xl font-bold mt-8 mb-2">Order Status Update</h2>
            <p>Orders with standard shipping ship within 2-6 business days. Orders with express shipping ship within 1-2 business days. Tracking information is automatically sent to your email. <br></br>
              More details about shipping can be found here.
            </p>
            </div>
          </div>

          <div className="leading-loose flex flex-col justify-center px-4">
            <h1 className="text-zinc-700 text-3xl mb-4">Contact Us</h1>
            <ContactForm/>
          </div>
        </div>
      </div>
    </main>
      <Footer/>
  </>
  )
}

export default Contact;
