import React, {useState} from 'react';
import Head from 'next/head'
import { sanityClient } from '/lib/sanity'
import {urlFor} from '/lib/sanity'
import Navigation from '@/components/Shared/Navigation'
import Footer from '@/components/Shared/Footer/footer'
import Link from 'next/link'


const Shop = ({shop}) => {
  
  const[isHovered, setIsHovered] = useState(null)
  
  //Destructuring shop object
  const[a,b,c, d] = shop 
  const [...arr] = [a,b,c,d]
 


  const contentBox = {
    width: '320px'
  }

  const divSize = {
    height: '420px',
  
  }


  const handleMouseEnter = (_id) => {
     setIsHovered(_id)
  } 

  const handleMouseLeave = (e) => {
    setIsHovered(null)  
  }


  

  

  
  return (
    <>
      <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation/>

      <main className="bg-white">
      <div className="container mx-auto justify-normal md:justify-center flex flex-row gap-x-48 gap-y-24 p-24 flex-wrap">
          {...arr.map((shopItems)=>{
            const{brandName, _id, slug, images, mainImage, mainImage2, productName, price, productDescription, shortDescription} = shopItems
            return (
              <>
                <Link href={`/shop/${slug.current}`} key={_id}>
                  <div className="text-zinc-700 cursor-pointer " key={_id} >
                    <div>
                      <div onMouseEnter={()=> handleMouseEnter(_id)} onMouseLeave={handleMouseLeave}  id={_id} className="shopImage">
                      <img src={ isHovered === _id ? urlFor(mainImage2.asset._ref) : urlFor(mainImage.asset._ref)} alt="plant-pots"apple  className="shopImage"/> 
                      </div>

                      <div className="mt-2">
                        <p className="text-sm">{brandName}</p>
                        <p className="font-bold">{productName}</p>
                        <p>${price}</p>

                        <div style={contentBox} className="line-clamp-4 mt-4" style={contentBox}>
                          <p className="text-sm text-bold ">
                            {shortDescription.map((x)=>{
                              return x.children[0].text
                            })}
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                </Link>
              </>
            )
          })}

      </div>
      </main>
      <Footer/>
    </>
  );
}

export default Shop;



const shopQuery = `*[_type == "product"]{
  brandName, 
  _id,
  slug,
  images,
  mainImage, 
  mainImage2,
  price, 
  productName,
  shortDescription,
  productDescription
}`

export async function getStaticProps() {
  const shop = await sanityClient.fetch(shopQuery)

  return {  
    props: {
      shop
    }
  }
}