import Navigation from '@/components/Shared/Navigation'
import Head from 'next/head'
import Footer from '@/components/Shared/Footer/footer'
import InputForm from '@/components/Shared/Forms/inputForm'
import Login from '@/components/Authorization/Login'
import Register from '@/components/Authorization/Register'
import { useGlobalContext } from '@/ Context/context'



const services = () => {
  const {isOpenMenu, isSignIn, isUserRegistered} = useGlobalContext()

  return (
    <>
    <Head>
      <title>Services</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    {isOpenMenu && <RespMenu/>}
    <Navigation/>
    {isSignIn && <Login/>}
    {isUserRegistered && <Register/>}

    <main>
      <div className="bg-white">
        <div className="w-screen">
          <img src='/images/tarotheadline.jpeg' alt="tarotcards" className="bg-zinc-700"/>
        </div>
        <div className="container mx-auto flex flex-col md:flex-row gap-12 p-24">
          <div className="mainTarotBox">
            <img src="/images/sideTarotImage.jpeg" alt="sideTarotImage"/>
          </div>
          <div className="flex flex-col gap-3 text-zinc-700">
            <h1 className="text-3xl font-bold">Book a Session Today</h1>
            <p className="text-lg w-3/4">Make an appointment today, to discuss your concerns with our resident psychic today.</p>

            <InputForm/>
            

          </div>
        </div>
      </div>
    </main>
    <Footer/>
    </>
  );


}

export default services