import Head from 'next/head'
import PortableTextComponent from '@/components/Shared/PortableTextComponent';
import Navigation from '@/components/Shared/Navigation'
import Footer from '@/components/Shared/Footer/footer'
import { sanityClient } from '/lib/sanity'

const Privacy = ({data}) => {
  const{privacy} = data
  const [privacyPolicy] = privacy


  return (
    <>
      <Head>
        <title>Privacy Policy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation/>
      <main className="bg-white">
        <div>
          <article className=" leading-loose text-lg w-fit md:w-1/2 items-center text-zinc-700">
            <PortableTextComponent detail={privacyPolicy}/>
          </article>
        </div>
      </main>
      <Footer/>
    </>
  )
}

//fetch the data using GROQ query
const privacyQuery = `*[_type == "privacy"]`

export async function getStaticProps() {
  const privacy = await sanityClient.fetch(privacyQuery)

  return {
    props: {
      data: {privacy}
    }
  }
}

export default Privacy;