import React from 'react';
import Navigation from '@/components/Shared/Navigation'
import { sanityClient } from '@/lib/dist/sanity.dev';
import { urlFor } from '/lib/sanity';
import Head from 'next/head'
import Footer from '@/components/Shared/Footer/footer';
import Link from 'next/link'


const Blog = ({blog}) => {
 

  const mainImageBlog = {
    width: '520px',
    height: 'auto',
    borderRadius: '0.5rem'
  }



  const smallImageBlog = {
    width: '340px',
    height: '250px',
    borderRadius: '0.5rem'
  }


  return (
    <>
    <Head>
        <title>Retrogold Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Navigation/>
    <main>
      <div className="text-zinc-100 md:px-12  p-44 bg-white">
        <div className="flex justify-start items-center">
          <div className="text-zinc-700">
            <h1 className="text-5xl ">Latest Stories</h1>
            <p className="text-medium mt-2">Uplifting, motivating stories about Wellness and the Home </p>
          </div>
        </div>
      
        <div className="grid grid-cols-3 mt-12">      
          <div className="col-span-3">

              <Link href={`/blog/${blog[0].slug.current}`}>
              <div className="flex md:flex-row flex-col bg-red-400 p-4 items-center rounded-xl cursor-pointer">
                <div className="ml-4">
                <div className="bg-red-500 w-fit px-2 mb-4 rounded-lg">
                  <span>{blog[0].tag}</span>
                </div>
                  <img src={urlFor(blog[0].main_image.asset._ref)} style={mainImageBlog}/>
                </div>

                <div>
                  <div className="text-xl font-light flex flex-col items-start p-12" >
                    <div>
                    {blog[0].description[0].children[0].text}
                    </div>
                    <div className="mt-24 cursor-pointer">
                    <span className="font-light text-sm bg-orange-400 rounded-lg px-2 py-1">Read more</span>
                    </div>
                  </div>  
                </div>
              </div>
              </Link>
          </div> 
        </div>
      
       
        <div className="flex flex-col items-center md:flex-row gap-6 mt-8">

          <div className="w-fit md:w-2/6 bg-orange-200 p-4 rounded-lg cursor-pointer">
            <Link href={`/blog/${blog[1].slug.current}`}>
              <div className="mb-2  bg-red-500 w-fit px-2 mb-4 rounded-lg">
                <span className="text-sm">{blog[0].tag}</span>
              </div>
              <img src={urlFor(blog[1].main_image.asset._ref)} style={smallImageBlog}/>
              <div className="text-sm font-light flex items-start mt-4 px-2 text-zinc-700">
                {blog[1].description[0].children[0].text}
              </div>

              <div className="flex justify-center mt-10 text-zinc-700 ">
                <span className="font-light text-sm bg-orange-400 rounded-lg px-2 py-1">Read more</span>
              </div>
            </Link>
          </div>
       
       

          <div className="w-fit md:w-2/6 bg-green-200 p-4 rounded-lg cursor-pointer">
          <Link href={`/blog/${blog[2].slug.current}`}>
              <div className="mb-2 bg-red-500 w-fit px-2 rounded-lg">
                <span className="text-sm">{blog[0].tag}</span>
              </div>
            <img src={urlFor(blog[2].main_image.asset._ref)} style={smallImageBlog}/>
              <div className="text-sm font-light flex items-start mt-4 px-2 text-zinc-700">
                {blog[2].description[0].children[0].text}
              </div>

              <div className="flex justify-center mt-16 text-zinc-700">
                <span className="font-light text-sm bg-orange-400 rounded-lg px-2 py-1">Read more</span>
              </div>
          </Link>
          </div>
        
       

       
          <div className="w-fit md:w-2/6 bg-pink-200 p-4 rounded-lg cursor-pointer">
            <Link href={`/blog/${blog[3].slug.current}`}>
              <div className="mb-2 bg-red-500 w-fit px-2 rounded-lg">
                <span className="text-sm">{blog[0].tag}</span>
              </div>
            <img src={urlFor(blog[3].main_image.asset._ref)} style={smallImageBlog}/>
              <div className="text-sm font-light flex flex-col items-start mt-4 px-2 text-zinc-700">
                {blog[3].description[0].children[0].text}
              </div>

                <div className="flex justify-center mt-6 text-zinc-700">
                  <span className="font-light text-sm bg-orange-400 rounded-lg px-2 py-1">Read more</span>
                </div>
            </Link>
          </div>
               
        
      </div>

       

      
    </div>
    </main>
   <Footer/>
    </>
  );
}

export default Blog;





//fetch the data using GROQ query
const blogQuery = `*[_type == "blog"]`

export async function getStaticProps() {
  const blog = await sanityClient.fetch(blogQuery)

  return {
    props: {
      blog
    }
  }
}