import PortableTextComponent from '@/components/Shared/PortableTextComponent';
import { sanityClient } from '@/lib/dist/sanity.dev';
import React from 'react';
import Navigation from '@/components/Shared/Navigation';
import Head from 'next/head'
import Footer from '@/components/Shared/Footer/footer';

const About = ({data}) => {
  const{about} = data
  const [aboutUs] = about
  console.log(aboutUs)


  return (
    <>
    <Head>
       <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Navigation/>
    <main>
    <div className="p-32 h-screen leading-loose">
      <PortableTextComponent detail={aboutUs}/>
    </div>
    </main>
    <Footer/>
    </>
  );
}

export default About;



const aboutInfo = `*[_type == 'about']`

export async function getStaticProps() {
  const about = await sanityClient.fetch(aboutInfo)

  return {
    props: {
      data: {about}
    }
  }
}

