import Head from 'next/head'
import { sanityClient } from '/lib/sanity'
import Navigation from '/components/Navigation'
import Hero from '/components/Hero'

export default function Home({hero}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-8">
        <Navigation/>
        <Hero hero={hero}/>
      </main>
    </>
  )
}

//fetch the data using GROQ query
const blogQuery = `*[_type == "blog"]`
const heroQuery = `*[_type == 'hero']`

// getStaticProps works when rendering from a headless CMS
export async function getStaticProps() {
  const blogs = await sanityClient.fetch(blogQuery)

  const hero = await sanityClient.fetch(heroQuery)
  
  return {
    props: {
      blogs,
      hero,
    }
  }
}