import Head from 'next/head'
import { sanityClient } from '/lib/sanity'
import Landing from '/components/Landing/Landing'
import Quotes from '/components/Quotes/Quotes'
import Experience from '/components/Experience/Experience'
import Blog from '../components/Blog/Blog'
import Footer from '@/components/Shared/Footer/Footer'
import Navigation from '@/components/Shared/Navigation/Navigation'
import WelcomeDrop from '@/components/Dropdown/WelcomeDrop'
import ProfileDrop from '@/components/Dropdown/ProfileDrop'
import Calltoaction from '../components/CallToAction/Calltoaction'
import { useGlobalContext } from '../ Context/context'
import RespMenu from '@/components/responsiveMenu/RespMenu'
import Login from '@/components/Authorization/Login'
import Register from '@/components/Authorization/Register'
import SearchDropdrown from '@/components/Dropdown/SearchDropdown'




export default function Home({ hero, quote, blog, calltoAction }) {
  const {
    isOpenMenu,
    isSignIn,
    isUserRegistered,
    isHovered,
    isDropdownHovered,
    isProfileHovered,
    isProfileDropdownHovered,
    isSearchValue
  } = useGlobalContext()

  const shouldShowDropdown = isHovered || isDropdownHovered
  const shouldProfileShowDropdown = isProfileHovered || isProfileDropdownHovered
  const showSearchDropdown = isSearchValue || false




  return (
    <>
      <Head>
        <title>Retrogold</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen">
        <div className="h-screen">
          <Navigation />
          {showSearchDropdown && <SearchDropdrown />}
          {isOpenMenu && <RespMenu />}
          {isSignIn && <Login />}
          {isUserRegistered && <Register />}
          {shouldShowDropdown && <WelcomeDrop />}
          {shouldProfileShowDropdown && <ProfileDrop />}
          <Landing hero={hero} />
          <Quotes quote={quote} />
          <Experience />
          <Blog blog={blog} />
          <Calltoaction calltoAction={calltoAction} />
          <Footer />
        </div>
      </main>
    </>
  )
}

//fetch the data using GROQ query
const blogQuery = `*[_type == "blog"]{
  description,
  "mainImage": main_image.asset->url,
  tag, 
  slug
}`
const heroQuery = `*[_type == 'hero']{
  headline,
  "heroImages":images.asset->url,
  _id
}`
const quoteQuery = `*[_type == 'quote']`
const calltoActionQuery = `*[_type ==  'callToAction']{
  headline, 
  sub_headline, 
  "mainImage":image.asset->url
}`


// getStaticProps works when rendering from a headless CMS
export async function getStaticProps() {
  const blog = await sanityClient.fetch(blogQuery)
  const hero = await sanityClient.fetch(heroQuery)
  const quote = await sanityClient.fetch(quoteQuery)
  const calltoAction = await sanityClient.fetch(calltoActionQuery)

  return {
    props: {
      hero,
      quote,
      blog,
      calltoAction,
    },
    revalidate: 60,
  }
}