import Head from 'next/head'
import { sanityClient } from '/lib/sanity'
import Hero from '@/components/Hero/Hero'
import Landing from '/components/Landing/Landing'
import Quotes from '/components/Quotes/Quotes'
import Experience from '/components/Experience/experience'


export default function Home({hero, quote}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen">
          <Landing hero={hero}/>  
          <Quotes quote={quote}/>
          <Experience/>
          <Quotes quote={quote}/>

          
      </main>
    </>
  )
}

//fetch the data using GROQ query
const blogQuery = `*[_type == "blog"]`
const heroQuery = `*[_type == 'hero']`
const quoteQuery = `*[_type == 'quote']`


// getStaticProps works when rendering from a headless CMS
export async function getStaticProps() {
  const blogs = await sanityClient.fetch(blogQuery)
  const hero = await sanityClient.fetch(heroQuery)
  const quote = await sanityClient.fetch(quoteQuery)

  return {
    props: {
      hero,
      quote,
    }
  }
}